[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seedstable = "HBktVPq8VSR42ugq3WoeHhqWqjSP8y2S4coVN7iRAAVD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/home/tt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
