[features]
seeds = false
skip-lint = false

[programs.devnet]
sdao_staking = "AnwNEDsBwSHqy3CdKLv2kieXD5QLqNqdVxEB8zCfPrrC"

[programs.localnet]
sdao_staking = "AnwNEDsBwSHqy3CdKLv2kieXD5QLqNqdVxEB8zCfPrrC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
